//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Urban.DCP.Web {
    
    
    public partial class ConfirmEmailPage {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Urban.DCP.Web.masters.Default Master {
            get {
                return ((Urban.DCP.Web.masters.Default)(base.Master));
            }
        }
    }
}
