//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furman.PDP.Web {
    
    
    public partial class NycTest {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Furman.PDP.Web.masters.Default Master {
            get {
                return ((Furman.PDP.Web.masters.Default)(base.Master));
            }
        }
    }
}
